import { Meta } from '@/components/Meta';
import { MainContent } from '@/components/Main';
import { files } from './prompts';
import { VideoMasonry } from '@/components/Waterfall';

const PromptsPage = ({ params }: { params: Record<string, string> }) => {
  const { locale = 'en' } = params;

  return (
    <>
      <Meta title={"Sora turns prompts into photorealistic videos - SoraMaker AI"} description={"Sora photorealistic videos, OpenAI Sora video generation, AI prompts to video with Sora, To help you more effective!"} locale={locale} />
      <MainContent>
        <h1 className="text-3xl font-bold tracking-tight text-main-text sm:text-4xl text-center">
          {`The latest videos generated by Sora`}
        </h1>
        <div className="w-full mt-6 text-center">
          <p>
            Collected from internet, welcome to submit your videos
          </p>
        </div>
        <div className='py-4 my-4 w-full px-20 overflow-auto'>
          <VideoMasonry videos={files} />
        </div>
      </MainContent>
    </>

  );
};

export default PromptsPage;
